name: Continuous integration
on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - "**.md"
      - "docs/**"
      - ".run/**"
      - ".idea/**"
      - ".config/**"
      - ".husky/**"

jobs:
  code-format:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    name: Code format
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install tools
        run: dotnet tool restore

      - name: Check code format
        run: dotnet csharpier . --check

  static-analysis:
    needs: code-format
    runs-on: ubuntu-latest
    timeout-minutes: 5
    name: Static analysis
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.x"

      - name: Install dependencies
        run: dotnet restore

      - name: Run .NET Code Analysis
        uses: dotnet/code-analysis@v1
        id: code-analysis
        with:
          build-breaking: true
          all-categories: all

  unit-tests:
    needs: static-analysis
    runs-on: ubuntu-latest
    timeout-minutes: 10
    name: Unit tests
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.x"

      - name: Install dependencies
        run: dotnet restore

      - name: Test
        run: dotnet test --logger trx --results-directory "UnitTestsResults"

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: UnitTests-Results
          path: UnitTestsResults
        if: ${{ always() }}
