name: Continuous integration
on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - "**.md"
      - "docs/**"
      - ".run/**"
      - ".idea/**"
      - ".config/**"
      - ".husky/**"

jobs:
  code-format:
    runs-on: ubuntu-latest
    name: Code format
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Install tools
        run: dotnet tool restore
        
      - name: Check code format
        run: dotnet csharpier --check
  
  
  unit-tests:
    needs: code-format
    runs-on: ubuntu-latest
    name: Unit tests
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'
        
      - name: Install dependencies
        run: dotnet restore
        
      - name: Test
        run: dotnet test --logger trx --results-directory "UnitTestsResults"
        
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: UnitTests-Results
          path: UnitTestsResults
        if: ${{ always() }} # Always when there are test failures
        