name: Deployment
on:
  pull_request:
    branches:
      - main

env:
  JwtSettings__Issuer: SensoBackend
  JwtSettings__Audience: SensoBackend
  JwtSettings__SecretKey: ${{ secrets.JWT_SECRET_KEY }}
  ConnectionStrings__DefaultConnection: ${{ secrets.PSQL_DEPLOYMENT_CONNECTION_STRING }}
  ASPNETCORE_URLS: https://+:8080
  ASPNETCORE_ENVIRONMENT: Production

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: "Set up .NET"
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "7.x"
          include-prerelease: true

      - name: "Build"
        run: |
          dotnet build --configuration Release SensoBackend/SensoBackend.csproj

      - name: "Publish"
        run: |
          dotnet publish --configuration Release SensoBackend --output dist

      - name: "Upload artifact"
        uses: actions/upload-artifact@v2
        with:
          name: "dist"
          path: "dist"

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: "Install SSH Key"
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_DEPLOYMENT_KEY }}
          known_hosts: "just-a-placeholder-so-we-dont-get-errors"

      - name: "Add known host"
        run: |
          ssh-keyscan -H ${{ secrets.DEPLOYMENT_HOST }} >> ~/.ssh/known_hosts

      - name: "Download artifact from build"
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: ./dist

      - name: test
        run: |
          ls -la
          echo "XD"
          ls -la ./dist

      - name: "Rsync to server"
        run: |
          rsync -avz ./dist/ ${{ secrets.DEPLOYMENT_USER }}@${{ secrets.DEPLOYMENT_HOST }}:/srv/senso/
